server:
  port: 8080

logging:
  level:
    root: info

image:
  base:
    user-identifier: base.png

tracker:
  days: 60

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      location: spring/temp
      max-file-size: 10MB
      max-request-size: 10MB