spring:
  config:
    import:
  profiles:
    group:
      local:
        - data
        - web
        - local-aws
      prod:
        - prod-data
        - web
        - prod-aws
      performance:
    default: local