server:
  port: 8080
  shutdown: graceful

logging:
  level:
    root: info

image:
  base:
    user-identifier: base.png

tracker:
  days: 60

ai:
  domain: ${AI_DOMAIN}
  port: 8000

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      location: spring/temp
      max-file-size: 10MB
      max-request-size: 10MB