spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update