= 퀘스트 API
:operation-http-request-title: HTTP 요청
:operation-http-response-title: HTTP 응답

== Command

=== 퀘스트 생성

operation::quest/saveNormalQuest[snippets='http-request,http-response,request-parts']

=== 퀘스트 세부 사항 설정

operation::quest/saveQuestDetail[snippets='http-request,http-response']

=== 퀘스트 라벨 구독

operation::quest/subscribeQuestLabel[snippets='http-request,http-response']

=== 퀘스트 라벨 리스트 전송

operation::quest/sendQuestLabels[snippets='http-request,http-response']

=== 그룹 퀘스트 생성

operation::quest/saveGroupQuest[snippets='http-request,http-response,request-parts']

=== 그룹 퀘스트 세부 사항 설정

operation::quest/saveGroupQuestDetail[snippets='http-request,http-response']

=== 그룹 퀘스트 라벨 구독

operation::quest/subscribeGroupQuestLabel[snippets='http-request,http-response']

=== 퀘스트 수락

operation::participant/saveParticipant[snippets='http-request,http-response']

=== 퀘스트 삭제

operation::participant/deleteParticipant[snippets='http-request,http-response'

=== 퀘스트 보상 받기

operation::participant/takeReward[snippets='http-request,http-response']

=== 퀘스트 완료

operation::participant/finish[snippets='http-request,http-response']

=== 퀘스트 계속 하기

operation::participant/continue[snippets='http-request,http-response']

== Query

=== 퀘스트 프로필 조회

operation::quest/getQuest[snippets='http-request,http-response']

=== 퀘스트 예시 사진 조회

operation::quest/getQuestImages[snippets='http-request,http-response']

=== 퀘스트 추천 받기

operation::quest/recommendQuest[snippets='http-request,http-response']

=== 퀘스트 검색

operation::quest/searchQuest[snippets='http-request,http-response']

=== 그룹 퀘스트 목록 조회

operation::quest/getGroupQuests[snippets='http-request,http-response']

=== 내 퀘스트 목록 조회

operation::participant/getMyQuests[snippets='http-request,http-response']