= 사용자 API
:operation-http-request-title: HTTP 요청
:operation-http-response-title: HTTP 응답

== Command

=== 회원가입

operation::user/save[snippets='http-request,http-response']

=== 프로필 수정

operation::user/update[snippets='http-request,http-response']

=== 계정 공개범위 수정

operation::user/updateVisibility[snippets='http-request,http-response']

=== 사용자 관심사 수정

operation::user/updateInterest[snippets='http-request,http-response']

=== 사용자 사진 수정

operation::user/updateImage[snippets='http-request,http-response,request-parts']

=== 사용자 사진 삭제

operation::user/deleteImage[snippets='http-request,http-response']

== Query

=== 프로필 조회

operation::user/read[snippets='http-request,http-response']

=== 내 프로필 조회

operation::user/readMyself[snippets='http-request,http-response']

=== 사용자 이름 중복 조회

operation::user/checkUsername[snippets='http-request,http-response']

=== 계정 공개 범위 조회

operation::user/readVisibility[snippets='http-request,http-response']

=== 사용자 검색

operation::user/search[snippets='http-request,http-response']